name: CI Non containerization build

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{secrets.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/test
      SPRING_DATASOURCE_USERNAME: ${{secrets.DB_USERNAME}}
      SPRING_DATASOURCE_PASSWORD: ${{secrets.DB_PASSWORD}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven (skip tests)
      run: mvn clean package -DskipTests
      
    - name: Create staging directory and copy JAR
      run: |
        mkdir -p staging
        cp target/*.jar staging/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: staging/
        
    - name: Print Build Metadata
      run: |
         echo "🔧 Build Metadata"
         echo "-----------------------------"
         echo "Repository: ${{ github.repository }}"
         echo "Workflow: ${{ github.workflow }}"
         echo "Job: ${{ github.job }}"
         echo "Run ID: ${{ github.run_id }}"
         echo "Run Number: ${{ github.run_number }}"
         echo "Actor (Triggered by): ${{ github.actor }}"
         echo "Event Name: ${{ github.event_name }}"
         echo "Commit SHA: ${{ github.sha }}"
         echo "Commit URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
         echo "Branch Ref: ${{ github.ref }}"
         echo "Branch Name: ${GITHUB_REF#refs/heads/}"
         echo "Build Time: $(date -u)"
         echo "Runner OS: ${{ runner.os }}"
         echo "Runner Name: ${{ runner.name }}"
         echo "Runner Arch: ${{ runner.arch }}"
         echo "Workflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
         echo "Repository URL: https://github.com/${{ github.repository }}"
         echo "Head Ref (PR): ${{ github.head_ref }}"
         echo "Base Ref (PR): ${{ github.base_ref }}"
         echo "Workspace: ${{ github.workspace }}"
         echo "GitHub Server URL: ${{ github.server_url }}"

